resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/waggonerjake/concourse-example

jobs:
  - name: hello-world-job
    plan:
      - get: repo
        trigger: true #Trigger this job when a new version of this resource is available
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ['Hello World!']
