resources:
  - name: repo
    type: git
    webhook_token: 'concours'
    check_ever: never
    source:
      uri: https://github.com/waggonerjake/concourse-example

jobs:
  - name: hello-world-job
    plan:
      - get: repo
        trigger: true #Trigger this job when a new version of this resource is available (e.g. when a push happens)
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: repo #since we run a get step earlier, we can retrieve the cloned repo here.
          run:
            path: cat
            args: ['repo/docker-compose.yml']
